### ISSUE TITLE
Kubernetes - logs - How are the module supposed to work?

### ISSUE THREAD

**Issue by acr92** [grafana/agent-modules#26]
Heya!

I stumbled upon this project, and it seems to be a potential great improvement for Grafana Agent configuration.

I'm trying to use the `Kubernetes` module for logs. I am running Grafana Agent in a DaemonSet configuration, with logs mounted to `/var/logs/pods` as ReadOnly. I've set `HOSTNAME` to:

```
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
```

My Loki is setup in a single tenant configuration with `auth_enabled: false`.

I've tried to use the examples from https://github.com/grafana/agent-modules/blob/main/example/kubernetes/logs/simple-single-tenant.river and https://github.com/grafana/agent-modules/blob/main/example/kubernetes/logs/single-tenant-custom-pipeline.river with no success.

The module itself shows up as "Unknown":
<img width="350" alt="image" src="https://github.com/grafana/agent-modules/assets/324506/b44b1c22-c4d5-419b-af74-1d77f0f3b9fe">

But if I go into a module it tends to show as Healthy:
<img width="1425" alt="image" src="https://github.com/grafana/agent-modules/assets/324506/47009d5d-246c-4889-874c-d762ed6b8319">

I've verified that my setup works with other configurations - like this https://gist.github.com/acr92/001ba1d61dd45aaa7d4ab8897ec81c55 - which does a small part of what the Kubernetes log module seems to do.

What are the next steps to debugging this further?

**Comment by bentonam** [comment]
@acr92  what version of the Grafana Agent and Loki are you running?

**Comment by acr92** [comment]
Grafana Agent 0.36.2
Loki 2.9.0

I've been able to get some modules to work, like the Spring Boot log formatter, or the `label_keep` one. But not the ones doing discovery.

**Comment by bentonam** [comment]
@acr92  I believe the issue here is that you're using Loki OSS which does not use basic auth, it uses a header `X-Scope-OrgID` header instead.  When I wrote this module I wrote it using Grafana Enterprise Logs, I made the password optional and was using the username and tenant from the same argument `loki_username`, but it was still being set the `basic_auth` block.  The mistake that I made in `all.river` was including the `loki.write` component directly and it should have been an argument instead.  

All of the other modules should work regardless OSS/Enterprise.  Essentially, copy the `modules/kubernetes/logs/all.river` and make that your `agent-config.river` changing the `loki.write` component to remove the `basic_auth` block and add the `tenant_id` argument to the `endpoint` block https://grafana.com/docs/agent/latest/flow/reference/components/loki.write/#endpoint-block and that should work for you.  There will need to be some clean up replacing some of the argument references but that should work.  

If you can wait a few days, I will rewrite the `all.river` to accept an argument of `forward_logs_to` where that would be your reference to a `loki.write "destination"` component i.e. `loki.write.destination.receiver`

**Comment by acr92** [comment]
Thank you for your thorough investigation, that does indeed seem to be the problem that I experienced. Yes, I can wait a few days.

**Comment by bentonam** [comment]
@acr92 these modules have been merged, please see the examples https://github.com/grafana/agent-modules/tree/main/example/kubernetes
